default_platform(:ios)

platform :ios do
  lane :build_and_tag do
    is_releasable = analyze_commits(match: 'v*')

    if is_releasable
      next_version = lane_context[SharedValues::RELEASE_NEXT_VERSION]

      UI.message("Starting build for: #{next_version}")

      gym(
        project: "Snyty.xcodeproj",
        scheme: "SnytyForRelease",
        destination: "generic/platform=iOS Simulator",
        skip_archive: true
      )

      add_git_tag(tag: "v#{next_version}")
      push_git_tags
    else
      UI.error("This build is not releasable")
    end

  end
end
